data <- read.table("D:/household_power_consumption/household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?")
time <- paste(data$Date,data$Time,sep = " ")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
data$Time <- strptime(time,format ="%d/%m/%Y %H:%M:%S")
newdata <- data[((data$Date=="2007-02-01") | (data$Date=="2007-02-02")),]
png(filename = "d:/ex1/plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(newdata$Time,newdata$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(newdata$Time,newdata$Voltage,type="l",ylab="Voltage",xlab="datetime",ylim=c(234,246))
plot(newdata$Time,newdata$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(newdata$Time,newdata$Sub_metering_2,type="l",col="red")
lines(newdata$Time,newdata$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),bty="n")
plot(newdata$Time,newdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()